TrajectoryPlannerROS:
  #Independent settings for the local costmap
  transform_tolerance: 0.3
  sim_time: 1.7
  sim_granularity: 0.025
  dwa: false #true
  vx_samples: 6 #3
  vtheta_samples: 20
  max_vel_x: 0.4 #0.65
  min_vel_x: 0.1
  max_rotational_vel: 1.2 #1.0
  min_in_place_rotational_vel: 0.8 #0.4
  xy_goal_tolerance: 0.15  #0.4
  yaw_goal_tolerance: 0.3 #0.05
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05
  holonomic_robot: false #true
  acc_lim_th: 0.75 #3.2
  acc_lim_x: 0.5 #2.5
  acc_lim_y: 0.5 #2.5
