local_costmap:
  publish_voxel_map: true
  global_frame: /odom # /map
  robot_base_frame: /base_footprint # /base_link
  update_frequency: 5.0
  publish_frequency: 5.0 #2.0
  static_map: false
  rolling_window: true
  width: 4.0 #6.0
  height: 4.0 #6.0
  resolution: 0.1 #0.025
  origin_x: 0.0
  origin_y: 0.0
