/* Auto-generated by genmsg_cpp for file /home/sebasgm/new_slam_karto/vslam_source/sba/msg/WorldPoint.msg */
#ifndef SBA_MESSAGE_WORLDPOINT_H
#define SBA_MESSAGE_WORLDPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace sba
{
template <class ContainerAllocator>
struct WorldPoint_ {
  typedef WorldPoint_<ContainerAllocator> Type;

  WorldPoint_()
  : index(0)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , w(0.0)
  {
  }

  WorldPoint_(const ContainerAllocator& _alloc)
  : index(0)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , w(0.0)
  {
  }

  typedef uint32_t _index_type;
  uint32_t index;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _w_type;
  double w;


  typedef boost::shared_ptr< ::sba::WorldPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sba::WorldPoint_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct WorldPoint
typedef  ::sba::WorldPoint_<std::allocator<void> > WorldPoint;

typedef boost::shared_ptr< ::sba::WorldPoint> WorldPointPtr;
typedef boost::shared_ptr< ::sba::WorldPoint const> WorldPointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sba::WorldPoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sba::WorldPoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sba

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sba::WorldPoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sba::WorldPoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sba::WorldPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "39d176a0b9c218409063b0b8e9be53a7";
  }

  static const char* value(const  ::sba::WorldPoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x39d176a0b9c21840ULL;
  static const uint64_t static_value2 = 0x9063b0b8e9be53a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::sba::WorldPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sba/WorldPoint";
  }

  static const char* value(const  ::sba::WorldPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sba::WorldPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# World Point parameters\n\
\n\
# Point index\n\
uint32 index\n\
\n\
# Coordinates in the world frame\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::sba::WorldPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::sba::WorldPoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sba::WorldPoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.index);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.w);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WorldPoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sba::WorldPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sba::WorldPoint_<ContainerAllocator> & v) 
  {
    s << indent << "index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.index);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SBA_MESSAGE_WORLDPOINT_H

